# Generated by Django 4.1.7 on 2023-03-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User Name: ')),
                ('prof', models.CharField(max_length=50, verbose_name='User Prof: ')),
                ('img', models.ImageField(upload_to='images', verbose_name='User Page: ')),
            ],
        ),
    ]
