# Generated by Django 4.1.7 on 2023-03-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Content Name: ')),
                ('text', models.TextField(verbose_name='Content Text: ')),
                ('img', models.ImageField(upload_to='images', verbose_name='Content Image: ')),
                ('buttonName', models.CharField(max_length=50, verbose_name='Content Button Name: ')),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': 'AboutMe', 'verbose_name_plural': 'About Me'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'UserInfo', 'verbose_name_plural': 'Users Info'},
        ),
    ]
