# Generated by Django 4.1.7 on 2023-03-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_content_alter_aboutme_options_alter_userinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=50, verbose_name='Skill Name: ')),
                ('skillText', models.TextField(verbose_name='Skill Text: ')),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='buttonName',
            field=models.CharField(max_length=100, verbose_name='Content Button Name: '),
        ),
    ]
