# Generated by Django 4.1.7 on 2023-03-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skill_alter_content_buttonname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Prof Name: ')),
                ('text', models.TextField(verbose_name='Prof Text: ')),
                ('img', models.ImageField(upload_to='images', verbose_name='Prof Image: ')),
            ],
            options={
                'verbose_name': 'Prof',
                'verbose_name_plural': 'Prof',
            },
        ),
    ]
