# Generated by Django 4.1.7 on 2023-03-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_prof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50, verbose_name='Image Name1: ')),
                ('name2', models.CharField(max_length=50, verbose_name='Image Name2: ')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
            ],
        ),
    ]
