# Generated by Django 4.1.7 on 2023-03-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Your Name: ')),
                ('mail', models.EmailField(max_length=254, verbose_name='Your Email: ')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject: ')),
                ('message', models.TextField(verbose_name='Your massage: ')),
            ],
        ),
    ]
